name: Daily Scala-AM tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '00 23 * * *' # Executes every night at 23:00.

jobs:
  # The compile job fetches the code and attempts to compile it.
  compile:
    name: Compile Scala-AM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: compile
  # The test-scalaam.lattice job executes the scalaam.lattice tests.
  test-lattice:
    name: Execute scalaam.lattice tests
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v2
      - uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: scalaam/testOnly scalaam.test.scalaam.lattice.*
  # The test-R5RS job executes the R5RS tests.
  test-R5RS:
    name: Execute primitive tests
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v2
      - uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: scalaam/testOnly scalaam.test.scalaam.language.scheme.*
  # The test-parser job executes the parser tests.
  test-parser:
    name: Execute parser tests
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v2
      - uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: scalaam/testOnly scalaam.test.parser.*
  # The test-soundness job executes the soundness tests.
  test-soundness:
    name: Execute soundness tests (using ${{ matrix.test_class }})
    runs-on: ubuntu-latest
    needs: compile
    timeout-minutes: 480 # 8 hours
    strategy:
      fail-fast: false
      matrix:
        test_class: [BigStepSchemeModFSoundnessTests, SmallStepSchemeModFSoundnessTests, SmallStepSchemeModConcSoundnessTests]
    steps:
      - uses: actions/checkout@v2
      - uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: scalaam/testOnly scalaam.test.soundness.${{ matrix.test_class }}
