name: Daily MAF evaluation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '00 23 * * *' # Executes every night at 23:00.
  push:
    branches: [ actions ]

jobs:
  # The compile job fetches the code and attempts to compile it.
  compile:
    name: Evaluate precision
    runs-on: ubuntu-latest
    timeout-minutes: 1 # TODO: change back to: 480 # 8 hours
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.15
      - name: Run precision benchmarks
        run: sbt "maf/runMain maf.cli.experiments.precision.DailyPrecisionBenchmarks"
      - name: Upload the benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: Precision benchmarks results
          path: benchOutput/precision/daily-precision-benchmarks.csv
      - name: Upload to Slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          path: benchOutput/precision/daily-precision-benchmarks.csv
          channel: maf-logs
          initial_comment: "Results of last night's precision evaluation."
  performance-evaluation:
    name: Execute performance evaluation with JMH
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.15
      - name: Run performance benchmarks
        run: sbt "maf/jmh:run -rf json -rff jmh-results-${GITHUB_SHA}.json"
      - name: Download previous benchmark results
        uses: actions/download-artifact@v2
        with:
          name: Performance evaluation results
          path: artifact/
      - name: Upload the benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: Performance evaluation results
          path: |
            artifact/*.json # previous runs
            code/jvm/jmh-results-${{ github.sha }}.json # current run
      - name: Install python dependencies
        uses: BSFishy/pip-action@v1
        with:
          packages: pandas
      - name: Generate graph
        run: python ./benchmarks/graphs.py
      - name: Upload graph to Slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          path: output.pdf
          channel: maf-logs
          initial_comment: "Results of last night's performance evaluation."