name: Scala-AM tests on action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # The compile job fetches the code and attempts to compile it.
  build:
    name: Compile Scala-AM
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Compile Scala-AM
      uses: lokkju/github-action-sbt@v0.2.2
      with:
        commands: compile
    - name: Run the tests
      uses: lokkju/github-action-sbt@v0.2.2
      with:
        commands: scalaam/testOnly -- -l SlowTest